### ISSUE TITLE
How did you create all the definitions?

### ISSUE THREAD

**Issue by vdisasm** [semuel/api_monitor_apis#1]
I want to add few myself. And I wonder have you created some tools to parse headers or is it available on Rohitab site?

Or have you made it all manually :) ?

Thanks

**Comment by shmuelfomberg** [comment]
When you download the API Monitor, you get a set of definitions with it. unfortunately, it is not maintained. so it lack some of the new APIs. 
I used that as base, and only added couple functions manually, when I found that they are missing. so no need for a tool.
The largest addition was an object. 
I really wish the author would have made it open source, so we could just contribute directly. oh well.

So anyway, you can download the SW, and then replace the original APIs with what you download from here. 

Of course, if you want me to add your definition to this repository, I'd be happy to. (you can clone the repository and then send a pull request)
As you can see in the README of this repository, I collected the various rules of the definition files.
